### ISSUE TITLE
which  files or folders   you copied from the old sdk 13?

### ISSUE THREAD

**Issue by vinorasu** [RandDruid/esp8266-deauth#1]
hi RandDruid,
, nicely done ,you got my admiration!
I am having issues replicating this ,mostly  the porting of sdk 13 to arduino environment. 

I did the modifications in "user_interface.h" (sdk13 and sdk 15 tested) but still the return from the wifi_send_pkt_freedom() is -1 ,as it 
has failed to send.  beacon and  data  packets return 0  as succeded to send.
I have IDE v. 1.6.5 +  esp8266 support 2.1.0-rc2

as test, I copied  the old sdk into the new one: 
from the staging release 2.1.0-rc2  I have an SDK folder that contains  the folders: INCLUDE, LD and LIB . I copied the 3 folders from sdk13 to the folder sdk of  arduino IDE , modified "user_interface.h" but then there are many errors , most probably I am not using the same files as you do.

Could you please explain which  files or folders   you copied from the old sdk 13?

I have put the same question on hackaday.io  please disregard one of them.
thanks in advance & regards

**Comment by RandDruid** [comment]
Sorry for the late answer, I was traveling.
I have Arduino 1.6.7 and "esp8266 by ESP8266 Community version 2.0.0-rc2" installed.
Declarations for "user_interface.h" I took from newer SDK. I took only lines related to "wifi_send_pkt_freedom()", not complete file. Because binaries are different.

Arduino IDE (or esp package) do not behave well when you changing versions of package in Boards Manager. The only way to do it (IMHO):
1) Close Arduiono IDE; 
2) Clean (or backup) Arduino IDE config from C:\Users...\AppData\Local\Arduino15 (you can leave one file - preferences.txt). 
3) Start Arduino IDE, and select desired package in Boards Manager.

Another possible problem - I think you can't send packets too fast. Insert some delay after "freedom()" or assign and wait for callback. I didn't analyze this issue closely, I just checked that Wireshark can see at least several DeAuth packets come through, and this was enough for my test.

**Comment by vinorasu** [comment]
hi RanDruid, 
thanks for the reply , I have it working with the 2.0.0-rc1 , the staging release did not work even with the  user_interface.h changes,so I will keep a backup of this  Arduino15 folder.
hopefully I will be able to implement WOL packets as well.
Best Regards
