### ISSUE TITLE
Help with setting up Arduino IDE

### ISSUE THREAD

**Issue by hronecviktor** [RandDruid/esp8266-deauth#4]
Hi, 

I've been trying to configure Arduino IDE with the patched sdk13, to no avail.
Couldn't make out the exact steps from the other issues.
Is there anybody who made this work (preferably on linux) and who could share the steps?
I have Arduino IDE 1.6.7 and tried both 2.0.0-rc1 (as vinorasu mentioned) and 2.1.0-rc2
I downloaded sdk15 via board manager, I copied the three directories from sdk13 to sdk15, prepended the four lines from hackaday project into user_interface.h and I am getting the following error: 

http://pastebin.com/y3jQFPnz

What am I doing wrong?

Thanks for help

**Comment by RandDruid** [comment]
Hello,
I can't give you my 100% exact steps, because I also tried many different approaches before made it work.
But general idea is the following: "free send" function was present in binaries (at least) one version of SDK earlier then it become available in ".h" header. When they publish this function in header, it was already protected from truly arbitrary packet sending. I discovered this by simple searche for function name through complete text of old SDK. And found it only in binary lib, not in header. That's how I come to idea of patch for ".h" file. After addition of these lines, Arduino can see function which is already present in the lib.
I don't think I made any other "mix" steps with SDK folders.
Another thing which I found out, is the pretty dirty work of Board Manager with these SDKs. My installation become screwed if I upgrade or downgrade SDK version from Arduino GUI. The only way to bring it back to working state is to clean ".arduino15" folder. Or rename it, to keep current as a backup. Then you can install version which you want to test. If you want to test another version - clean folder first.

Finally, I can simply 7zip and pastebin mine "Arduino15" folder, which, I think, have all magic inside. But it is from Windows installation.
I don't want to publish it on GitHub because that would be SDK license violation.

**Comment by hronecviktor** [comment]
I made it work in the meantime, can pickup .11 management frames in wireshark. Looks like patching the header file might be enough after all, though neither I can 100% vouch for that ._. I might have done some magic without knowing, tried a lot of things. I will backup the whole folder in case something gets messed up again. And I've seen somebody publishing the whole sdk13 on github somewhere, for the same purpose of transmitting management frames. Thanks for help
